Events/urls.py
from django.urls import path
#from . import views
from Events.views import Events,AddEvent,AddMember

app_name = 'story6'

urlpatterns=[
    path('',Events,name="Events"),
    path('AddEvent',AddEvent,name='AddEvent'),
    path('AddMember/<event_id>',AddMember,name='AddMember')
]

main/urls.py
from django.urls import path,include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('educations', views.educations, name='educations'),
    path('experiences', views.experiences, name='experiences'),
    path('project', views.project, name='project'),
    path('story1', views.story1, name='story1'),
    path('contact', views.contact, name='contact'),
    path('story5/', include('story5.urls',namespace='story5')),
    path('Events/', include('Events.urls',namespace='Events')),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('Events/', include('Events.urls',namespace='Events')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('story9/',include('story9.urls')),
]

Events/models.py
from django.db import models

# Create your models here.
class FormEvent(models.Model):
    Event_Name = models.CharField(max_length=20, )

    def __str__(self):
        return self.Event_Name

class FormMember(models.Model):
    First_Name = models.CharField(max_length=20)
    Last_Name = models.CharField(max_length=20)
    event = models.ForeignKey(FormEvent, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.First_Name

Events/forms.py
from django.forms import ModelForm
from django import forms
from .models import FormEvent,FormMember

class EventForm(forms.ModelForm):
    class Meta:
        model = FormEvent
        fields = [
            'Event_Name',
        ]

        widgets = {
            'Event_Name' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Event Name',
                    'style':'#FF0C55',
                    'id':'Event_Name',
                    'name':'Event_Name',
                    
                }
            ),
          
        }

class MemberForm(forms.ModelForm):
    class Meta:
        model = FormMember
        fields = [
            'First_Name',
            'Last_Name'
        ]

        widgets = {
            'First_Name' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Your First Name',
                    'style':'#FF0C55',
                    'id':'First_Name',
                    'name':'First_Name',
                    
                }
            ),
            'Last_Name' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Enter Your Last Name',
                    'style':'#FF0C55',
                    'id':'Last_Name',
                    'name':'Last_Name',
                    
                }
            ),
          
        }

Events/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .forms import EventForm,MemberForm
from .models import FormMember,FormEvent

# Create your views here.

def Events(request):
    form = FormEvent.objects.all()
    member  = FormMember.objects.all()
    response={
        'form':form,
        'member':member
    }

    return render(request,'Events/Events.html',response)

def AddEvent(request):
    model = FormEvent
    form = EventForm()

    if request.method=="POST":
        form = EventForm(request.POST)
        if form.is_valid():
            Event_Name = request.POST.get("Event_Name")
        form.save()

        context = {
            'form' : form
        }

        return redirect('Events:Events')
        
    else:
        context = {
            'form' : form
        }
    
    return render(request,'Events/AddEvent.html',context) 
    
    #return render(request,'Events/AddEvent.html',response) 

def AddMember(request,event_id):
    model=FormMember
    form = MemberForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            Member=FormMember.objects.filter(event=event_id)
            event=FormEvent.objects.get(id=event_id)
            form.save()
            return redirect('Events:Events')

    context = {
        'form' : form,
        }

    return render(request,'Events/AddMember.html',context)  

Events/templates/Events/AddEvent.html
{% extends 'base.html' %}

{% load static %}

<html>

    
        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="#"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                <a href="{% url 'Events:AddEvent' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">ADD EVENTS</button></a>
                
                <a href="{% url 'Events:Events' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EVENTS</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}
        <h2 id='font-color' class='center'>EVENT FORM</h2>
        
        <h2>
            <form method="POST" id='font-color'>
                {% csrf_token %}
                
                <div class="form-group">
                    {{form.as_p}}
                </div>
        
                <button type="submit" id="buttonpink" class="btn btn-default">Submit</button>
            </form>
        </h2>

    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
        </body>
</html>

Events/templates/Events/AddMember.html
{% extends 'base.html' %}

{% load static %}

<html>

    
        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="#"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                <a href="{% url 'Events:AddEvent' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">ADD EVENTS</button></a>
                
                <a href="{% url 'Events:Events' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EVENTS</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}
        <h2 id='font-color' class='center'>MEMBER REGISTRATION FORM</h2>
        
        <h2>
            <form method="POST" id='font-color'>
                {% csrf_token %}
                
                <div class="form-group">
                    {{form.as_p}}
                </div>
        
                <button type="submit" id="buttonpink" class="btn btn-default">Submit</button>
            </form>
        </h2>


    {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
        </body>
</html>

Events/templates/Events/Events.html
{% extends 'base.html' %}

{% load static %}

<html>

    
        {% block header1 %}
        <body class="body">
            <h1 class="h1">
                <a href="#"><span id="span">KAYSA SWA</span></a>
                <ul></ul>
                <a href="{% url 'Events:AddEvent' %}">
                    <button id="buttonpink" type="button" class="btn btn-secondary">ADD EVENT</button></a>
                
                <a href="{% url 'Events:Events' %}">
                    <button id="buttonorange" type="button" class="btn btn-secondary">EVENTS</button></a>

            </h1>

        {% endblock header1 %}

        {% block content %}
            <h2 id='font-color' class='center'>EVENTS</h2>

            <h3 class="center">
                
                <div class="row" style="padding: 20px;display: flex;justify-content: center;">
                    {% for event in form %}
                        <div class="col-sm-6" style="margin-top: 30px">
                            <div class="card">
                                <div class="card-body">
                                <h3 class="card-title">{{event.Event_Name}}</h3>
                                {% for member in member %}
                                    <p class="card-text">{{member.First_Name}} {{member.Last_Name}}</p>
                                {% endfor %}
                                <a href="{% url 'Events:AddMember' event.id %}" class="btn btn-primary" style="background: linear-gradient(90deg, #F17B41 , #CD4BC9, #E56487);">JOIN US</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                
            </h3>

        {% endblock content %}
        
       
        {% block header3 %}

            <h3 class="h3">FIND ME HERE
                <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                    <div class="center">
                        <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                            <i class="fab fa-instagram" id="link2"></i></a>
        
                            <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                            <i class="fab fa-linkedin"  id="link1"></i></a>
                            
                            <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                            <i class="fas fa-envelope" id="link1"></i></a>
                            
                            <i class="fab fa-line" id="link1"></i>
                    </div>
            </h3>

        {% endblock header3 %}
        
  

            </h4>

             
                
            </h4>
        </body>
</html>