main/urls.py
from django.urls import path,include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('educations', views.educations, name='educations'),
    path('experiences', views.experiences, name='experiences'),
    path('project', views.project, name='project'),
    path('story1', views.story1, name='story1'),
    path('contact', views.contact, name='contact'),
    path('story5/', include('story5.urls',namespace='story5')),
    path('Events/', include('Events.urls',namespace='Events')),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
    path('Events/', include('Events.urls',namespace='Events')),
    path('story7/',include('story7.urls')),
    path('story8/',include('story8.urls')),
    path('story9/',include('story9.urls')),
]

story8/urls.py
from django.urls import path

from .views import home,fungsi_data

app_name = 'story8'

urlpatterns = [
    path('', home, name='home'),
    path('data/',fungsi_data,name='fungsi_data')
]

story9/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,loginFunc,logoutFunc,signup

app_name = 'story9'

urlpatterns=[
    path('home',home,name='home'),
    path('login',loginFunc,name='login'),
    path('logout',logoutFunc,name='logout'),
    path('signup',signup,name='signup')
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request,"story9/hi.html")

def loginFunc(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('story9:home')
    else:
        form=AuthenticationForm()
    return render(request,"story9/login.html",{'form':form})

def logoutFunc(request):
    logout(request)
    return redirect('/')

def signup(request):
    if request.method == "POST":
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            user=form.save()
            login(reques.user)
            return redirect('story9:home')
    else:
        form=UserCreationForm()
    return render(request,"story9/signup.html",{'form':form})

story9/templates/story9/hi.html
{% extends 'base.html' %}

{% load static %}


<html> 
    
    {% block header1 %}
    <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>

            </h1>

        {% endblock header1 %}
    
    {% block content %}

    <style>
        .title3 {
            line-height: 2.9rem;
            text-align: center;
            font-size: 3rem;
            width: 100%;
            height:auto;
            color: #FF0C55;
        }

        #book,#logout{
            border-color: #FF0C55;
            background-color: #FF0C55;
            color: white;
        }

        h4{
            color: #FF0C55;
            position: relative;
            margin: auto;
            text-align: center;
            margin-bottom:3vw;
        }

        

    </style>

    {% if user.is_authenticated %}

    <div class="main">
        <h3 class="title3" style="margin-top:4vw;"> Hello, <span>{{ user }}</span></h3>
        <div class="centercenter" style="text-align: center">
        <h6 class="title3" style="margin-bottom:7vw;">
                You can use Book Search Engine -> <a href="{% url 'story8:home' %}">
                    <button class="btn btn-outline-primary" id="book">Book Search Engine</button> 
                </a>
        </h6>
        <h4> or do you want to logout? </h4>
        <a href="{% url 'story9:logout' %}">
                <button class="btn btn-outline-primary" id="logout">Logout</button>
        </a>
        </div>
    </div>

    {% else %}

    <div class="main">
        <h3 class="title3" style="margin-top:8vw;">
                Please  <a href="{% url 'story9:login' %}">login! </a>
        </h3>
    </div>

    {% endif %}

    {% endblock content %}
    </body>
        
    {% block header3 %}

        <h3 class="h3" style="margin-top: 5rem;">FIND ME HERE
            <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>

                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
        </h3>

    {% endblock header3 %}



        </h4>

        
            
        </h4>
    </body>

</html>

story9/templates/story9/login.html
{% extends 'base.html' %}

{% load static %}


<html> 
    
    {% block header1 %}
    <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>

            </h1>

        {% endblock header1 %}
    
    {% block content %}

    <style>

        h1{
            text-align: center;
            color: #FF0C55;
            margin-bottom: 5vw;
            line-height: 2.9rem;
            text-align: center;
            font-size: 3rem;
            font-weight: 900;
            width: 100%;
            height:auto;
        }


        .login-page{
           display: none;
           width: 400px;
           height: 530px;
           position: relative;
           margin: auto;
           background: #f9f9f9;
           padding: 5px;
           border-radius: 21px;

           
        }

        .login-form{
            top: 3vw;
            position: relative;
            margin: auto;
            width: 280px;
            transition: .5s;
        
        }

        .login-form input{
            font-family: "Roboto",sans-serif;
            outline: none;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
            background: transparent;
            cursor: pointer;
            border-radius: 21px;
        }

        p a:link {
            color: #FF0C55;
            text-decoration: underline;
            cursor: pointer;
            }

            /* visited link */
        p a:visited {
            color: #FF0C55;
            text-decoration: underline;
            cursor: pointer;
            }

            /* selected link */
        p a:active {
            color: #FF0C55;
            text-decoration: none;
            cursor: pointer;
            }
        
        a:link {
            text-decoration: none;
            }

            /* visited link */
        a:visited {
            text-decoration: none;
            }

            /* selected link */
        a:active {
            text-decoration: none;
            }
        
        button{
            text-align: center;
            position: relative;
            left:28vw;
            font-family: "Roboto",sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #FF0C55;
            width: 30vw;
            border: 0;
            padding: 15px;
            color: #ffffff;
            font-size: 14px;
            cursor: pointer;
            border-radius: 21px;
            margin-bottom: 3vw;
        }

        .centercenter{
            position: relative;
            margin: auto;
            text-align: center;
            color: #FF0C55;
            display: flex;
            align-items: center;
        }

        h4{
            color: #FF0C55;
            position: relative;
            margin: auto;
            text-align: center;
            margin-bottom:3vw;
        }

    </style>

    <div>
        {% if user.is_authenticated %}
        <div class="container">
            <h1>You're In</h1>
            <h4>Do you want to logout?</h4>
            <div class="centercenter">
                <a href="{% url 'story9:logout' %}">
                    <button class="btn btn-primary active" style="background-color: transparent;border-color: #FF0C55;" id="logout">LogOut</button>
                </a>
            </div>
            
        </div>

        {% else %}

        <div class="container">
            <h1>Log In to Use Book Search Engine</h1>
            <button id="button" onclick="document.getElementById('loginpage').style.display='block'">LogIn</button>"
        </div>
    
        <div id="loginpage" class = "login-page">
            <div class ="login-form">
                <form action="{% url 'story9:login' %}" method="POST">
                    {% csrf_token %}
                    {{form.as_table}}
                    <input type="submit" value="Login" style="color:white;background-color: #FF0C55;">
                </form>
                <p>Let's try logging in. Input "admin" as username and "kaysa123" as password</p>
                <p>or do you want to make your own account? Try signup <a href="{% url 'story9:signup' %}">here</a></p>
            </div>
        </div>

    {% endif %}
</div>
    {% endblock content %}
    </body>
        
    {% block header3 %}

        <h3 class="h3" style="margin-top: 5rem;">FIND ME HERE
            <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>

                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
        </h3>

    {% endblock header3 %}



        </h4>

        
            
        </h4>
    </body>

</html>

story9/templates/story9/signup.html
{% extends 'base.html' %}

{% load static %}


<html> 
    
    {% block header1 %}
    <body class="body">
            <h1 class="h1">
                <a href="{% url 'main:home' %}"><span id="span">KAYSA SWA</span></a>

            </h1>

        {% endblock header1 %}
    
    {% block content %}

    <style>

        h1{
            line-height: 2.9rem;
            text-align: center;
            font-size: 3rem;
            font-weight: 900;
            width: 100%;
            height:auto;
            color: #FF0C55;
            margin-bottom: 3vw;
        }


        .login-page{
           display: none;
           width: 400px;
           height: 800px;
           position: relative;
           margin: auto;
           background: #f9f9f9;
           padding: 5px;
           border-radius: 21px;

           
        }

        .login-form{
            top: 3vw;
            position: relative;
            margin: auto;
            width: 280px;
            transition: .5s;
        
        }

        .login-form input{
            font-family: "Roboto",sans-serif;
            outline: none;
            background: #f2f2f2;
            width: 100%;
            border: #FF0C55;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
            background: transparent;
            cursor: pointer;
            border-radius: 21px;
        }

        p a:link {
            color: #FF0C55;
            text-decoration: underline;
            cursor: pointer;
            }

            /* visited link */
        p a:visited {
            color: #FF0C55;
            text-decoration: underline;
            cursor: pointer;
            }

            /* selected link */
        p a:active {
            color: #FF0C55;
            text-decoration: none;
            cursor: pointer;
            }
        
        a:link {
            text-decoration: none;
            }

            /* visited link */
        a:visited {
            text-decoration: none;
            }

            /* selected link */
        a:active {
            text-decoration: none;
            }
        
        button{
            text-align: center;
            position: relative;
            left:28vw;
            font-family: "Roboto",sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #FF0C55;
            width: 30vw;
            border: 0;
            padding: 15px;
            color: #ffffff;
            font-size: 14px;
            cursor: pointer;
            border-radius: 21px;
            margin-bottom: 3vw;
        }

        .centercenter{
            position: relative;
            margin: auto;
            text-align: center;
            color: #FF0C55;
            display: flex;
            align-items: center;
        }

        h4{
            color: #FF0C55;
            position: relative;
            margin: auto;
            text-align: center;
            margin-bottom:3vw;
        }

        

    </style>

  
    <div>
        {% if user.is_authenticated %}
        <div class="container">
            <h1>You're In</h1>
            <h4>Do you want to logout?</h4>
            <div class="centercenter">
                <a href="{% url 'story9:logout' %}">
                    <button class="btn btn-primary active" style="background-color: transparent;border-color: #FF0C55;" id="logout">LogOut</button>
                </a>
            </div>
            
        </div>

        {% else %}

        <div class="container">
            <h1>Sign Up</h1>
            <button id="button" onclick="document.getElementById('loginpage').style.display='block'">SignUp</button>"
        </div>
    
        <div id="loginpage" class = "login-page">
            <div class ="login-form">
                <form action="{% url 'story9:signup' %}" method="POST">
                    {% csrf_token %}
                    {{form.as_table}}
                    <input type="submit" value="Signup" style="color:white;background-color: #FF0C55;">
                </form>
                <p>LogIn <a href="{% url 'story9:login' %}">here</a></p>
            </div>
        </div>

    {% endif %}
</div>
    {% endblock content %}
    </body>
        
    {% block header3 %}

        <h3 class="h3" style="margin-top: 5rem;">FIND ME HERE
            <script src="https://kit.fontawesome.com/56fc67844f.js" crossorigin="anonymous"></script>
                <div class="center">
                    <a href="https://www.instagram.com/kaysasy_/" target="_blank">
                        <i class="fab fa-instagram" id="link2"></i></a>

                        <a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4" target="_blank">
                        <i class="fab fa-linkedin"  id="link1"></i></a>
                        
                        <a href="https://mail.google.com/mail/u/0/#inbox?compose=NZVHGDkdRDwnxgckKZgqFpxfFnMBqkGrVcSHCSVPWVZvKrMTHhQHhLjRXBvCxjmkFjVNpg" target="_blank">
                        <i class="fas fa-envelope" id="link1"></i></a>
                        
                        <i class="fab fa-line" id="link1"></i>
                </div>
        </h3>

    {% endblock header3 %}



        </h4>

        
            
        </h4>
    </body>

</html>